// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asxzncvrwtjqtjoedisw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzeHpuY3Zyd3RqcXRqb2VkaXN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMTM5MzIsImV4cCI6MjA2OTU4OTkzMn0.e2kvV5eDsVq4JtjerVLTv9A7CK8SUXN4BX1O2XqEDKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});